const express = require('express')
const router = express.Router()

router.use('/auth', require('./auth'))
router.use('/admissions', require('./admissions'))
router.use('/jobs', require('./jobs'))
router.use('/activities', require('./activities'))
router.use('/dashboard', require('./dashboard'))
router.use('/children', require('./children'))
router.use('/applications', require('./applications'))
router.use('/nanny', require('./nanny'))
router.use('/safety', require('./safety'))
router.use('/sos', require('./sos'))
router.use('/marketplace', require('./marketplace'))
router.use('/adoption', require('./adoption'))
router.use('/adoption-admin', require('./adoption_admin'))
router.use('/learning', require('./learning'))
router.use('/daycare', require('./daycare'))
router.use('/families', require('./families'))
router.use('/messages', require('./messages'))
router.use('/admin', require('./admin'))
router.use('/child', require('./childModeRoutes'))
router.use('/upload', require('./upload'))
router.use('/ai', require('./ai'))
router.use('/gps', require('./gps'))
router.use('/notifications', require('./notifications'))
module.exports = router
